"""Add resource_type

Revision ID: 281a7a878c4d
Revises: 693e589aeb84
Create Date: 2025-02-12 19:30:00.739924

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '281a7a878c4d'
down_revision: Union[str, None] = '693e589aeb84'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('resource_type', sa.String(), nullable=True))
    op.create_index(op.f('ix_resources_resource_type'), 'resources', ['resource_type'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_resources_resource_type'), table_name='resources')
    op.drop_column('resources', 'resource_type')
    # ### end Alembic commands ###
