"""Add employ_id to resources

Revision ID: 693e589aeb84
Revises: b68a7efad5c2
Create Date: 2025-02-12 18:49:09.412758

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '693e589aeb84'
down_revision: Union[str, None] = 'b68a7efad5c2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('resources', sa.Column('employ_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'resources', 'employs', ['employ_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'resources', type_='foreignkey')
    op.drop_column('resources', 'employ_id')
    # ### end Alembic commands ###
